CREATE DATABASE AIG_SCHOOLS 
ON(
NAME = AIG_SCHOOLS,
FILENAME = 'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AIG_SCHOOLS.MDF',
SIZE= 100MB,
MAXSIZE= UNLIMITED,
FILEGROWTH= 5MB
)

LOG ON(
NAME = AIG_SCHOOLS_LOG,
FILENAME = 'c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\AIG_SCHOOLS.LDF',
SIZE= 100MB,
MAXSIZE= 1000MB,
FILEGROWTH= 6MB
)